=== annocjx/Awesome-Java-Notebook/JavaWeb/xml/src/plan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <element name="teaching-plan">
  	<complexType>
  		<sequence>
  			<element name="course" minOccurs="1" maxOccurs="100">
  				<complexType>
  				 	<sequence>
  				 		<element name="course-name" type="string"></element>
  				 		<element name="class-hour">
  				 		 <simpleType>
  				 		 	<restriction base="integer">
  				 		 		<minInclusive value="20"></minInclusive>
  				 		 		<maxInclusive value="110"></maxInclusive>
  				 		 	</restriction>
  				 		 </simpleType>
  				 		</element>
  				 		<element name="exam-form" type="string"></element>
  				 	</sequence>
  				 	<attribute name="id" type="string" use="required"></attribute>
  				</complexType>
  			</element>
  		</sequence>
  	</complexType>
  </element>
  
</schema>

=== annocjx/Awesome-Java-Notebook/JavaWeb/xml/src/planschema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 教学计划根节点 -->
<teaching-plan
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="plan.xsd">
	<!-- 课程 -->
	<course id="1">
		<course-name>大学英语</course-name>
		<class-hour>60</class-hour>
		<exam-form>考试</exam-form>
	</course>
	<course id="2">
		<course-name>高等数学</course-name>
		<class-hour>70</class-hour>
		<exam-form>考试</exam-form>
	</course>
	<course id="3">
		<course-name>计算机应用基础</course-name>
		<class-hour>108</class-hour>
		<exam-form>上机考试</exam-form>
	</course>
	<course id="4">
		<course-name>Java</course-name>
		<class-hour>100</class-hour>
		<exam-form>上机考试</exam-form>
	</course>
	<course id="5">
		<course-name>C++</course-name>
		<class-hour>10</class-hour>
		<exam-form>上机考试</exam-form>
	</course>
</teaching-plan>
