=== annocjx/Awesome-Java-Notebook/JavaWeb/xml/bin/hr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 创建约束 -->
<!ELEMENT hr (employee+)>
<!ELEMENT employee (name,age,salary,department)>

<!-- 属性约束 -->
<!ATTLIST employee no CDATA "">

<!-- 定义标签的值 都是纯文本-->
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT department (dname,address)>
<!ELEMENT dname (#PCDATA)>
<!ELEMENT address (#PCDATA)>

=== annocjx/Awesome-Java-Notebook/JavaWeb/xml/bin/hr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hr SYSTEM "hr.dtd"><!-- 引入dtd文件约束 -->
<hr>
	<employee no="1301">
		<name>张三</name>
		<age>12</age>
		<salary>4000</salary>
		<department>
			<dname>BOOS1</dname>
			<address>BEIJING1</address>
		</department>
	</employee>
	<employee no="1302">
		<name>李四</name>
		<age>21</age>
		<salary>3000</salary>
		<department>
			<dname>BOOS2</dname>
			<address>BEIJING2</address>
		</department>
	</employee>
	<employee no="1303">
		<name>王刚但</name>
		<age>18</age>
		<salary>1000</salary>
		<department>
			<dname>技术部</dname>
			<address>1-1-103</address>
		</department>
	</employee>
	<employee no="1304">
		<name>王刚但1</name>
		<age>18</age>
		<salary>1000</salary>
		<department>
			<dname>技术部</dname>
			<address>1-1-103</address>
		</department>
	</employee>
	<employee no="1305">
		<name>王刚但2</name>
		<age>18</age>
		<salary>1000</salary>
		<department>
			<dname>技术部</dname>
			<address>1-1-103</address>
		</department>
	</employee>
	<employee no="1306">
		<name>王刚但3</name>
		<age>18</age>
		<salary>1000</salary>
		<department>
			<dname>技术部</dname>
			<address>1-1-103</address>
		</department>
	</employee>
</hr>
